// =============================================================================
// SRT Fixer — Cloudflare Worker Backend
// Receives SRT entries + original text, calls Beeknoee AI to fix transcription
// errors, returns corrected entries.
// =============================================================================

const API_ENDPOINT = 'https://platform.beeknoee.com/api/v1/chat/completions';
const DEFAULT_API_KEY = 'sk-bee-837f622110f44d64a3ca729a77695314';
const CHUNK_SIZE = 25;
const MAX_RETRIES = 3;
const FETCH_TIMEOUT_MS = 60_000; // 60s per API call
const CHUNK_DELAY_MS = 3_000; // 3s delay between chunks to avoid rate limits

// ─── CORS ────────────────────────────────────────────────────────────────────

export const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

export function corsResponse(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...CORS_HEADERS },
  });
}

// ─── Key Parsing ────────────────────────────────────────────────────────────

function parseKeys(keysSource) {
  const keys = (keysSource || '')
    .split('\n')
    .map((k) => k.trim())
    .filter((k) => k.length > 0);
  if (keys.length === 0) throw new Error('No API keys configured');
  return keys;
}

// ─── AI Interaction ──────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are a subtitle correction tool. You will receive:
1. Original content/script text
2. A list of subtitle entries (generated by speech-to-text, may contain errors)

Your job: Compare each subtitle entry against the original content and fix any transcription errors. The subtitles follow the chronological order of the original content.

Rules:
- Fix text ONLY, do not change entry numbers or structure
- If a subtitle is correct, keep it as-is
- Match the language of the original content
- Maintain the natural segmentation of subtitles (don't merge or split entries)
- Return ONLY a JSON array with the corrected text for each entry
- Keep each entry's text on a single element (do not split lines within one entry)

Return format (JSON array, same order as input):
["corrected text 1", "corrected text 2", ...]

IMPORTANT: Output ONLY the JSON array. No explanation, no markdown, no extra text.`;

function buildUserPrompt(originalText, entries) {
  const numbered = entries
    .map((e, i) => `${i + 1}: ${e.text}`)
    .join('\n');

  return `Original content:
---
${originalText}
---

Subtitle entries to fix:
${numbered}

Return ONLY the JSON array of corrected texts, in the same order. No explanation.`;
}

/**
 * Extract a JSON array from the AI response text, handling markdown fences
 * and other wrappers the model might add.
 */
function parseAIResponse(raw) {
  let cleaned = raw.trim();

  // Strip markdown code fences (```json ... ``` or ``` ... ```)
  const fenceMatch = cleaned.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenceMatch) {
    cleaned = fenceMatch[1].trim();
  }

  // Attempt direct parse
  try {
    const parsed = JSON.parse(cleaned);
    if (Array.isArray(parsed)) return parsed;
    throw new Error('Parsed value is not an array');
  } catch {
    // Try to find the first [...] block in the text
    const arrayMatch = cleaned.match(/\[[\s\S]*\]/);
    if (arrayMatch) {
      const parsed = JSON.parse(arrayMatch[0]);
      if (Array.isArray(parsed)) return parsed;
    }
    throw new Error('Failed to parse AI response as JSON array');
  }
}

/**
 * Call the Beeknoee API for a single chunk with a specific key + retries.
 */
async function callAIWithKey(entries, originalText, key, model) {
  const messages = [
    { role: 'system', content: SYSTEM_PROMPT },
    { role: 'user', content: buildUserPrompt(originalText, entries) },
  ];

  let lastError = null;

  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    let response;
    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), FETCH_TIMEOUT_MS);

      response = await fetch(API_ENDPOINT, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${key}`,
        },
        body: JSON.stringify({
          model,
          messages,
          temperature: 0.3,
          max_tokens: 8192,
        }),
        signal: controller.signal,
      });

      clearTimeout(timeoutId);
    } catch (err) {
      const msg = err.name === 'AbortError'
        ? 'API request timed out'
        : `Network error: ${err.message}`;
      lastError = new Error(msg);
      continue;
    }

    const responseText = await response.text();

    // Rate-limit — wait and retry
    if (response.status === 429) {
      const retryAfter = parseInt(response.headers.get('retry-after') || '5', 10);
      const waitMs = Math.min(retryAfter * 1000, 15_000);
      await new Promise(r => setTimeout(r, waitMs));
      lastError = new Error(`Rate limited (HTTP 429), waited ${waitMs}ms`);
      continue;
    }

    // Other error
    if (!response.ok) {
      lastError = new Error(`API error (HTTP ${response.status}): ${responseText.slice(0, 300)}`);
      continue;
    }

    // Parse the successful response
    let parsed;
    try {
      parsed = JSON.parse(responseText);
    } catch {
      lastError = new Error('API returned non-JSON response');
      continue;
    }

    const content = parsed?.choices?.[0]?.message?.content;
    if (!content) {
      lastError = new Error('API response missing choices[0].message.content');
      continue;
    }

    try {
      return parseAIResponse(content);
    } catch (err) {
      lastError = new Error(`AI response parse error: ${err.message}`);
      continue;
    }
  }

  throw lastError || new Error('Max retries exceeded');
}

// ─── Chunking ────────────────────────────────────────────────────────────────

function chunkArray(arr, size) {
  const chunks = [];
  for (let i = 0; i < arr.length; i += size) {
    chunks.push(arr.slice(i, i + size));
  }
  return chunks;
}

// ─── Main Fix Logic ──────────────────────────────────────────────────────────

export async function handleFix(request, env) {
  // ── Parse & validate request body ──
  let body;
  try {
    body = await request.json();
  } catch {
    return corsResponse({ success: false, error: 'Invalid JSON body' }, 400);
  }

  const { srtEntries, originalText, apiKeys, model: requestModel } = body || {};

  if (!Array.isArray(srtEntries) || srtEntries.length === 0) {
    return corsResponse(
      { success: false, error: 'srtEntries must be a non-empty array' },
      400,
    );
  }

  if (typeof originalText !== 'string' || originalText.trim().length === 0) {
    return corsResponse(
      { success: false, error: 'originalText must be a non-empty string' },
      400,
    );
  }

  // Validate each entry has required fields
  for (let i = 0; i < srtEntries.length; i++) {
    const e = srtEntries[i];
    if (
      e == null ||
      typeof e.index === 'undefined' ||
      typeof e.timeCode !== 'string' ||
      typeof e.text !== 'string'
    ) {
      return corsResponse(
        {
          success: false,
          error: `Invalid entry at position ${i}: must have index, timeCode, and text`,
        },
        400,
      );
    }
  }

  // ── Setup ──
  // Priority: client keys > env var > hardcoded default
  const keysSource = (typeof apiKeys === 'string' && apiKeys.trim())
    ? apiKeys
    : (env.API_KEYS || DEFAULT_API_KEY);
  let keys;
  try {
    keys = parseKeys(keysSource);
  } catch (err) {
    return corsResponse({ success: false, error: err.message }, 400);
  }
  const model = (typeof requestModel === 'string' && requestModel.trim())
    ? requestModel
    : (env.MODEL || 'glm-4.7-flash');

  // ── Chunk & process (parallel batches) ──
  // Each batch runs up to N chunks in parallel (one per key).
  // e.g. 3 keys, 7 chunks → batch1: [c1,c2,c3], batch2: [c4,c5,c6], batch3: [c7]
  const chunks = chunkArray(srtEntries, CHUNK_SIZE);
  const batches = chunkArray(chunks, keys.length);
  const allCorrected = new Array(chunks.length);

  try {
    let chunkOffset = 0;
    for (let bi = 0; bi < batches.length; bi++) {
      if (bi > 0) {
        await new Promise(r => setTimeout(r, CHUNK_DELAY_MS));
      }

      const batch = batches[bi];
      const results = await Promise.all(
        batch.map((chunk, i) =>
          callAIWithKey(chunk, originalText, keys[i % keys.length], model)
        )
      );

      for (let i = 0; i < results.length; i++) {
        if (results[i].length !== batch[i].length) {
          return corsResponse(
            {
              success: false,
              error: `AI returned ${results[i].length} entries but expected ${batch[i].length}`,
            },
            502,
          );
        }
        allCorrected[chunkOffset + i] = results[i];
      }
      chunkOffset += batch.length;
    }
  } catch (err) {
    const status = err.message.includes('exhausted') || err.message.includes('rate-limited') ? 503 : 502;
    return corsResponse({ success: false, error: `Processing failed: ${err.message}` }, status);
  }

  // Flatten chunk results into a single array
  const flatCorrected = allCorrected.flat();

  // ── Build response ──
  let fixedCount = 0;

  const fixed = srtEntries.map((entry, i) => {
    const correctedText = String(flatCorrected[i]);
    const changed = correctedText !== entry.text;
    if (changed) fixedCount++;

    return {
      index: entry.index,
      timeCode: entry.timeCode,
      text: correctedText,
      original: entry.text,
      changed,
    };
  });

  return corsResponse({
    success: true,
    fixed,
    stats: {
      total: srtEntries.length,
      errors: fixedCount,
      fixed: fixedCount,
    },
  });
}

// Exports: handleFix, corsResponse, CORS_HEADERS
