// =============================================================================
// SRT Fixer — Cloudflare Worker Backend
// Receives SRT entries + original text, calls Beeknoee AI to fix transcription
// errors, returns corrected entries.
// =============================================================================

const API_ENDPOINT = 'https://platform.beeknoee.com/api/v1/chat/completions';
const CHUNK_SIZE = 25;
const MAX_RETRIES = 3;
const FETCH_TIMEOUT_MS = 60_000; // 60s per API call

// ─── CORS ────────────────────────────────────────────────────────────────────

export const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type',
};

export function corsResponse(body, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...CORS_HEADERS },
  });
}

// ─── Key Manager ─────────────────────────────────────────────────────────────

class KeyManager {
  constructor(keysString) {
    this.keys = (keysString || '')
      .split('\n')
      .map((k) => k.trim())
      .filter((k) => k.length > 0);
    this.currentIndex = 0;
    this.exhaustedKeys = new Set();
  }

  getKey() {
    if (this.keys.length === 0) {
      throw new Error('No API keys configured');
    }

    const total = this.keys.length;
    let checked = 0;

    while (checked < total) {
      const key = this.keys[this.currentIndex % total];
      this.currentIndex = (this.currentIndex + 1) % total;

      if (!this.exhaustedKeys.has(key)) {
        return key;
      }
      checked++;
    }

    throw new Error('All API keys exhausted');
  }

  markExhausted(key) {
    this.exhaustedKeys.add(key);
  }

  get allExhausted() {
    return this.exhaustedKeys.size >= this.keys.length;
  }
}

// ─── AI Interaction ──────────────────────────────────────────────────────────

const SYSTEM_PROMPT = `You are a subtitle correction tool. You will receive:
1. Original content/script text
2. A list of subtitle entries (generated by speech-to-text, may contain errors)

Your job: Compare each subtitle entry against the original content and fix any transcription errors. The subtitles follow the chronological order of the original content.

Rules:
- Fix text ONLY, do not change entry numbers or structure
- If a subtitle is correct, keep it as-is
- Match the language of the original content
- Maintain the natural segmentation of subtitles (don't merge or split entries)
- Return ONLY a JSON array with the corrected text for each entry
- Keep each entry's text on a single element (do not split lines within one entry)

Return format (JSON array, same order as input):
["corrected text 1", "corrected text 2", ...]

IMPORTANT: Output ONLY the JSON array. No explanation, no markdown, no extra text.`;

function buildUserPrompt(originalText, entries) {
  const numbered = entries
    .map((e, i) => `${i + 1}: ${e.text}`)
    .join('\n');

  return `Original content:
---
${originalText}
---

Subtitle entries to fix:
${numbered}

Return ONLY the JSON array of corrected texts, in the same order. No explanation.`;
}

/**
 * Extract a JSON array from the AI response text, handling markdown fences
 * and other wrappers the model might add.
 */
function parseAIResponse(raw) {
  let cleaned = raw.trim();

  // Strip markdown code fences (```json ... ``` or ``` ... ```)
  const fenceMatch = cleaned.match(/```(?:json)?\s*([\s\S]*?)```/);
  if (fenceMatch) {
    cleaned = fenceMatch[1].trim();
  }

  // Attempt direct parse
  try {
    const parsed = JSON.parse(cleaned);
    if (Array.isArray(parsed)) return parsed;
    throw new Error('Parsed value is not an array');
  } catch {
    // Try to find the first [...] block in the text
    const arrayMatch = cleaned.match(/\[[\s\S]*\]/);
    if (arrayMatch) {
      const parsed = JSON.parse(arrayMatch[0]);
      if (Array.isArray(parsed)) return parsed;
    }
    throw new Error('Failed to parse AI response as JSON array');
  }
}

/**
 * Returns true if the error indicates a quota/rate-limit issue that
 * warrants rotating to the next API key.
 */
function isQuotaError(status, body) {
  if (status === 429) return true;
  if (typeof body === 'string') {
    const lower = body.toLowerCase();
    return (
      lower.includes('quota') ||
      lower.includes('rate limit') ||
      lower.includes('exceeded') ||
      lower.includes('insufficient_quota')
    );
  }
  return false;
}

/**
 * Call the Beeknoee API for a single chunk with retry + key rotation.
 */
async function callAI(entries, originalText, keyManager, model) {
  const messages = [
    { role: 'system', content: SYSTEM_PROMPT },
    { role: 'user', content: buildUserPrompt(originalText, entries) },
  ];

  let lastError = null;

  for (let attempt = 0; attempt < MAX_RETRIES; attempt++) {
    let key;
    try {
      key = keyManager.getKey();
    } catch (err) {
      throw new Error('All API keys exhausted');
    }

    let response;
    try {
      response = await fetch(API_ENDPOINT, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${key}`,
        },
        body: JSON.stringify({
          model,
          messages,
          temperature: 0.3,
          max_tokens: 8192,
        }),
      });
    } catch (err) {
      lastError = new Error(`Network error: ${err.message}`);
      // Network error — retry with same key (attempt counter already increments)
      continue;
    }

    const responseText = await response.text();

    // Quota / rate-limit — rotate key, retry
    if (isQuotaError(response.status, responseText)) {
      keyManager.markExhausted(key);
      lastError = new Error(`Key exhausted (HTTP ${response.status})`);
      continue;
    }

    // Other non-OK status — retry once with same key, then fail
    if (!response.ok) {
      lastError = new Error(`API error ${response.status}: ${responseText.slice(0, 300)}`);
      // Allow one more retry (the loop increments attempt)
      continue;
    }

    // Parse the successful response
    let parsed;
    try {
      parsed = JSON.parse(responseText);
    } catch {
      lastError = new Error('API returned non-JSON response');
      continue;
    }

    const content = parsed?.choices?.[0]?.message?.content;
    if (!content) {
      lastError = new Error('API response missing choices[0].message.content');
      continue;
    }

    try {
      return parseAIResponse(content);
    } catch (err) {
      lastError = new Error(`AI response parse error: ${err.message}`);
      continue;
    }
  }

  throw lastError || new Error('Max retries exceeded');
}

// ─── Chunking ────────────────────────────────────────────────────────────────

function chunkArray(arr, size) {
  const chunks = [];
  for (let i = 0; i < arr.length; i += size) {
    chunks.push(arr.slice(i, i + size));
  }
  return chunks;
}

// ─── Main Fix Logic ──────────────────────────────────────────────────────────

export async function handleFix(request, env) {
  // ── Parse & validate request body ──
  let body;
  try {
    body = await request.json();
  } catch {
    return corsResponse({ success: false, error: 'Invalid JSON body' }, 400);
  }

  const { srtEntries, originalText } = body || {};

  if (!Array.isArray(srtEntries) || srtEntries.length === 0) {
    return corsResponse(
      { success: false, error: 'srtEntries must be a non-empty array' },
      400,
    );
  }

  if (typeof originalText !== 'string' || originalText.trim().length === 0) {
    return corsResponse(
      { success: false, error: 'originalText must be a non-empty string' },
      400,
    );
  }

  // Validate each entry has required fields
  for (let i = 0; i < srtEntries.length; i++) {
    const e = srtEntries[i];
    if (
      e == null ||
      typeof e.index === 'undefined' ||
      typeof e.timeCode !== 'string' ||
      typeof e.text !== 'string'
    ) {
      return corsResponse(
        {
          success: false,
          error: `Invalid entry at position ${i}: must have index, timeCode, and text`,
        },
        400,
      );
    }
  }

  // ── Setup ──
  const keyManager = new KeyManager(env.API_KEYS);
  const model = env.MODEL || 'glm-4.7-flash';

  // ── Chunk & process ──
  const chunks = chunkArray(srtEntries, CHUNK_SIZE);
  let allCorrected = [];

  try {
    for (const chunk of chunks) {
      const correctedTexts = await callAI(chunk, originalText, keyManager, model);

      if (correctedTexts.length !== chunk.length) {
        return corsResponse(
          {
            success: false,
            error: `AI returned ${correctedTexts.length} entries but expected ${chunk.length}`,
          },
          502,
        );
      }

      allCorrected = allCorrected.concat(correctedTexts);
    }
  } catch (err) {
    const status = err.message.includes('exhausted') ? 503 : 502;
    return corsResponse({ success: false, error: err.message }, status);
  }

  // ── Build response ──
  let fixedCount = 0;

  const fixed = srtEntries.map((entry, i) => {
    const correctedText = String(allCorrected[i]);
    const changed = correctedText !== entry.text;
    if (changed) fixedCount++;

    return {
      index: entry.index,
      timeCode: entry.timeCode,
      text: correctedText,
      original: entry.text,
      changed,
    };
  });

  return corsResponse({
    success: true,
    fixed,
    stats: {
      total: srtEntries.length,
      errors: fixedCount,
      fixed: fixedCount,
    },
  });
}

// Exports: handleFix, corsResponse, CORS_HEADERS
